/**
 * generateSupportedCommands.mjs
 *
 * Emits the supported LaTeX command allowlist (from latexToUnicodeMath.mjs) into
 * a C++ header consumed by the native input detector in the *sibling* repo:
 *
 *   MathIntellisenseRN/windows/MathIntellisenseRN/SupportedLatexCommands.g.h
 *
 * This script lives next to latexToUnicodeMath.mjs (the source of truth) but
 * writes ACROSS REPOS — it assumes MathIntellisense and MathIntellisenseRN are
 * siblings under .../source/repos/.  Re-run whenever the converter's command
 * coverage changes.  Usage:  node scripts/generateSupportedCommands.mjs
 */
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import { SUPPORTED_COMMANDS } from './latexToUnicodeMath.mjs';

const scriptDir = dirname(fileURLToPath(import.meta.url));
const outPath = resolve(
  scriptDir,
  '../../MathIntellisenseRN/windows/MathIntellisenseRN/SupportedLatexCommands.g.h',
);

// The detector only ever scans \[A-Za-z]+ tokens, so keep only pure-letter
// command names (drops map keys like '%', '\\', '|', ',' that can't be matched).
const names = [...SUPPORTED_COMMANDS]
  .filter((name) => /^[A-Za-z]+$/.test(name))
  .sort();

const entries = names.map((n) => `"${n}"`).join(', ');

const header = `#pragma once
#include <string>
#include <unordered_set>

// GENERATED by MathIntellisense/scripts/generateSupportedCommands.mjs — do not edit by hand.
// Source of truth: MathIntellisense/scripts/latexToUnicodeMath.mjs (SUPPORTED_COMMANDS).
// Re-run the generator after changing the converter's command coverage.

inline const std::unordered_set<std::string>& SupportedLatexCommands() {
  static const std::unordered_set<std::string> kCommands = {
    ${entries}
  };
  return kCommands;
}
`;

writeFileSync(outPath, header, 'utf8');
console.log(`Wrote ${names.length} commands to ${outPath}`);
