/**
 * High-school equation set.
 * Covers Algebra 1/2, Geometry, Trigonometry, Pre-Calculus,
 * AP Calculus AB/BC, AP Statistics, and standard HS Physics.
 */
export const HS_EQUATION_NAMES = new Set([

  // ── Algebra ───────────────────────────────────────────────────────────────
  "exponent product rule",
  "exponent quotient rule",
  "exponent power rule",
  "negative exponent",
  "fractional exponent",
  "logarithm product rule",
  "logarithm quotient rule",
  "logarithm power rule",
  "logarithm inverse",
  "perfect square trinomial",
  "perfect square trinomial subtraction",
  "completing the square",
  "quadratic formula",
  "discriminant",
  "difference of squares",
  "sum of cubes",
  "difference of cubes",
  "binomial theorem",
  "geometric series",
  "infinite geometric series",
  "arithmetic series",
  "change of base",
  "permutation",
  "combination",
  "nth term of arithmetic sequence",
  "nth term of geometric sequence",
  "vertex form of a parabola",
  "exponential growth and decay",
  "direct variation",
  "inverse variation",
  "distance rate time",
  "absolute value equation",

  // ── Geometry ──────────────────────────────────────────────────────────────
  "slope",
  "slope intercept form",
  "point slope form",
  "standard form of a line",
  "Pythagorean theorem",
  "distance formula",
  "midpoint formula",
  "equation of a circle",
  "area of a circle",
  "circumference of a circle",
  "area of a triangle",
  "Heron's formula",
  "area of a rectangle",
  "area of a trapezoid",
  "area of an ellipse",
  "volume of a sphere",
  "surface area of a sphere",
  "volume of a cylinder",
  "volume of a cone",
  "volume of a cube",
  "volume of a rectangular prism",
  "volume of a pyramid",
  "surface area of a cylinder",
  "surface area of a cone",
  "surface area of a rectangular prism",

  // ── Trigonometry ──────────────────────────────────────────────────────────
  "sine ratio",
  "cosine ratio",
  "tangent ratio",
  "cosecant reciprocal identity",
  "secant reciprocal identity",
  "cotangent reciprocal identity",
  "tangent quotient identity",
  "cotangent quotient identity",
  "degree to radian conversion",
  "radian to degree conversion",
  "Pythagorean identity",
  "secant identity",
  "cosecant identity",
  "sine double angle formula",
  "cosine double angle formula",
  "cosine double angle formula 2",
  "cosine double angle formula 3",
  "tangent double angle formula",
  "sine addition formula",
  "sine subtraction formula",
  "cosine addition formula",
  "cosine subtraction formula",
  "tangent addition formula",
  "tangent subtraction formula",
  "law of sines",
  "law of cosines",
  "Euler's formula",
  "arc length",
  "area of a sector",
  "area of a triangle using sine",
  "sine half angle formula",
  "cosine half angle formula",
  "tangent half angle formula",

  // ── Conic Sections ────────────────────────────────────────────────────────
  "standard form of an ellipse",
  "standard form of a hyperbola",
  "standard form of a parabola",

  // ── AP Calculus ───────────────────────────────────────────────────────────
  "chain rule",
  "product rule",
  "quotient rule",
  "fundamental theorem of calculus",
  "definite integral",
  "integration by parts",
  "Taylor series",
  "Maclaurin series",
  "L'Hopital's rule",
  "power rule for derivatives",
  "derivative of sine",
  "derivative of cosine",
  "derivative of tangent",
  "derivative of cotangent",
  "derivative of secant",
  "derivative of cosecant",
  "derivative of e to the x",
  "derivative of natural log",
  "derivative of a to the x",
  "derivative of arcsin",
  "derivative of arccos",
  "derivative of arctan",
  "power rule for integration",
  "mean value theorem",
  "Rolle's theorem",
  "squeeze theorem",
  "limit of sin x over x",
  "limit of 1 minus cos x over x",
  "average value of a function",
  "disk method",
  "washer method",
  "shell method",
  "arc length of a curve",
  "integral of 1 over x",
  "integral of e to the x",
  "integral of sine",
  "integral of cosine",
  "integral of tangent",
  "integral of sec squared",
  "integral of 1 over sqrt 1 minus x squared",
  "integral of 1 over 1 plus x squared",
  "p-series convergence",
  "ratio test",

  // ── AP Statistics ─────────────────────────────────────────────────────────
  "sample mean",
  "sample variance",
  "population standard deviation",
  "z-score",
  "Bayes theorem",
  "expected value discrete",
  "addition rule for probability",
  "conditional probability formula",
  "multiplication rule for probability",
  "binomial probability",
  "complement rule",
  "law of total probability",
  "standard error of the mean",
  "confidence interval for mean",
  "t-test statistic",
  "Pearson correlation",
  "OLS slope",
  "OLS intercept",
  "simple linear regression",
  "R squared",

  // ── Complex Numbers (Pre-Calc/Honors) ─────────────────────────────────────
  "Euler's identity",
  "modulus of a complex number",
  "de Moivre's theorem",

  // ── Discrete Mathematics ──────────────────────────────────────────────────
  "sum of first n integers",
  "sum of first n squares",
  "mathematical induction",

  // ── Financial Mathematics (HS Business Math) ──────────────────────────────
  "simple interest",
  "compound interest",
  "continuously compounded interest",
  "future value",
  "present value",

  // ── Physics - Mechanics ───────────────────────────────────────────────────
  "Newton's second law",
  "kinetic energy formula",
  "gravitational potential energy near surface",
  "kinematic velocity",
  "kinematic position",
  "kinematic velocity squared",
  "kinematic average velocity",
  "Newton's law of universal gravitation",
  "momentum",
  "impulse",
  "conservation of momentum",
  "work",
  "power",
  "centripetal acceleration",
  "centripetal force",
  "torque",
  "Hooke's law",
  "period of a spring",
  "period of a pendulum",

  // ── Physics - Thermodynamics ──────────────────────────────────────────────
  "ideal gas law",
  "first law of thermodynamics",
  "heat transfer",
  "thermal linear expansion",
  "Carnot efficiency",

  // ── Physics - Electromagnetism ────────────────────────────────────────────
  "Coulomb's law",
  "Ohm's law",
  "electric field from point charge",
  "electric potential energy",
  "electric potential",
  "capacitance",
  "electrical power",
  "resistors in series",
  "resistors in parallel",
  "magnetic force on a charge",
  "magnetic force on a wire",
  "Faraday's law",

  // ── Physics - Waves ───────────────────────────────────────────────────────
  "wave speed equation",
  "wave frequency and period",
  "Snell's law",
  "thin lens equation",
  "magnification",
  "Doppler effect",

  // ── Physics - Modern ──────────────────────────────────────────────────────
  "Einstein mass-energy equivalence",
  "photoelectric effect",
  "de Broglie wavelength",
  "Heisenberg uncertainty principle",
]);
